/**
 * External Template for Locomotion Diary Binder
 * Contains the Master List of Documents (Indian Scenario)
 * 
 * Format: window.BINDER_TEMPLATE_DEFAULT = [ ... ];
 * This matches the format generated by the "Export Template" feature.
 */

window.BINDER_TEMPLATE_DEFAULT = [
    {
        "type": "section",
        "title": "I. Vital Identity & Civil Documents",
        "children": [
            {
                "type": "section",
                "title": "Birth Certificate",
                "children": [
                    { "type": "field", "title": "Date of Birth", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "Place of Birth", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Registration Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Date of Issue", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "Municipality/Panchayat", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Aadhaar Card",
                "children": [
                    { "type": "field", "title": "Aadhaar Number (12-digit)", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Linked Mobile Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Virtual ID (VID)", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "PAN Card",
                "children": [
                    { "type": "field", "title": "PAN Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Name as on Card", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Passport",
                "children": [
                    { "type": "field", "title": "Passport Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Expiry Date", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "Place of Issue", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "ECR / Non-ECR Status", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Voter ID (EPIC)",
                "children": [
                    { "type": "field", "title": "EPIC Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Polling Station", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Assembly Constituency", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Ration Card",
                "children": [
                    { "type": "field", "title": "Card Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Card Type (APL/BPL/AAY)", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "FPS (Shop) Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Members Included", "fieldType": "note", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Domicile / Nativity Certificate",
                "children": [
                    { "type": "field", "title": "Certificate Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Issuing Authority", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Validity Period", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Community / Caste Certificate",
                "children": [
                    { "type": "field", "title": "Caste Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Certificate Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Creamy/Non-Creamy Layer", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Marriage Certificate",
                "children": [
                    { "type": "field", "title": "Date of Marriage", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "Registration Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Place of Registration", "fieldType": "text", "value": "" }
                ]
            }
        ]
    },
    {
        "type": "section",
        "title": "II. Education & Co-Curricular",
        "children": [
            {
                "type": "section",
                "title": "10th (SSLC) Details",
                "children": [
                    { "type": "field", "title": "Register/Roll Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Certificate Serial No.", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Board Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Year of Passing", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "12th (HSC) Details",
                "children": [
                    { "type": "field", "title": "Register/Roll Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Certificate Serial No.", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Board Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Year of Passing", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Degree / Diploma (Graduation)",
                "children": [
                    { "type": "field", "title": "University Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Register Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Class/Grade", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Year of Convocation", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Transfer & Migration Certs",
                "children": [
                    { "type": "field", "title": "TC Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Admission Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Institution Name", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Entrance Exams (NEET/JEE/etc)",
                "children": [
                    { "type": "field", "title": "Roll Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Rank / Percentile", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Login Credentials", "fieldType": "note", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Scholarships",
                "children": [
                    { "type": "field", "title": "Scheme Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Registration ID", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Linked Bank Account", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Co-Curricular (NCC/NSS/Sports)",
                "children": [
                    { "type": "field", "title": "Activity Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Grade/Level", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Camp/Event Dates", "fieldType": "text", "value": "" }
                ]
            }
        ]
    },
    {
        "type": "section",
        "title": "III. Professional & Career",
        "children": [
            {
                "type": "section",
                "title": "Current Employment",
                "children": [
                    { "type": "field", "title": "Company Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Employee Code", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Designation", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Date of Joining", "fieldType": "date", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Previous Employment",
                "children": [
                    { "type": "field", "title": "Start Date", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "End Date", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "Reason for Leaving", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Salary & PF",
                "children": [
                    { "type": "field", "title": "UAN (Universal Account No)", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "PF Member ID", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "EPFO Password", "fieldType": "password", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Tax Documents",
                "children": [
                    { "type": "field", "title": "Assessment Year", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Gross Income", "fieldType": "currency", "value": "" },
                    { "type": "field", "title": "Tax Paid", "fieldType": "currency", "value": "" }
                ]
            }
        ]
    },
    {
        "type": "section",
        "title": "IV. Property, Assets & Local Body",
        "children": [
            {
                "type": "section",
                "title": "Property Title Deed",
                "children": [
                    { "type": "field", "title": "Document Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "SRO Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Survey / Re-survey No", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Extent of Land", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Land Tax (Karam)",
                "children": [
                    { "type": "field", "title": "Thandaper Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Village Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Last Payment Date", "fieldType": "date", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Building Tax",
                "children": [
                    { "type": "field", "title": "Assessment Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Ward & Door Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Local Body Name", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Utilities (Electricity/Water)",
                "children": [
                    { "type": "field", "title": "Consumer Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Section Office", "fieldType": "text", "value": "" }
                ]
            }
        ]
    },
    {
        "type": "section",
        "title": "V. Health & Medical History",
        "children": [
            {
                "type": "section",
                "title": "Vaccinations",
                "children": [
                    { "type": "field", "title": "Cowin Cert ID", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Key Vaccine Dates", "fieldType": "note", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Medical History",
                "children": [
                    { "type": "field", "title": "Blood Group", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Surgeries/Discharges", "fieldType": "note", "value": "" },
                    { "type": "field", "title": "Daily Prescriptions", "fieldType": "note", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Health Insurance",
                "children": [
                    { "type": "field", "title": "Policy Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "TPA Name", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Helpline Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Renewal Date", "fieldType": "date", "value": "" }
                ]
            }
        ]
    },
    {
        "type": "section",
        "title": "VI. Vehicle & Transport",
        "children": [
            {
                "type": "section",
                "title": "RC Book",
                "children": [
                    { "type": "field", "title": "Vehicle Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Chassis Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Engine Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Expiry/Renewal Date", "fieldType": "date", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Driving License",
                "children": [
                    { "type": "field", "title": "DL Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Valid Until (Non-Transport)", "fieldType": "date", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Pollution Cert (PUC)",
                "children": [
                    { "type": "field", "title": "PUC Expiry Date", "fieldType": "date", "value": "" }
                ]
            }
        ]
    },
    {
        "type": "section",
        "title": "VII. Other Important Docs",
        "children": [
            {
                "type": "section",
                "title": "LPG Gas Connection",
                "children": [
                    { "type": "field", "title": "Consumer Number", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Distributor Details", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "SV Number", "fieldType": "text", "value": "" }
                ]
            },
            {
                "type": "section",
                "title": "Legacy & Wills",
                "children": [
                    { "type": "field", "title": "Will Executed Date", "fieldType": "date", "value": "" },
                    { "type": "field", "title": "Location of Original", "fieldType": "text", "value": "" },
                    { "type": "field", "title": "Witness Names", "fieldType": "note", "value": "" }
                ]
            }
        ]
    }
];
